sudo: required
language: php
addons:
  chrome: stable
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
php:
- 7.1
env:
- TRAVIS_NODE_VERSION="8"
matrix:
  fast_finish: true
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g yarn
- yarn
script:
- yarn run test
